---
name: KMART Report
url: https://myorg.jamfcloud.com
credentials: base_64_encoded_username:password
api_requests: 4
api_timeout: 10
reports:
  buildings_not_linked: true
  categories_not_linked: true
  departments_not_linked: true
  ebooks_no_scope: true
  ibeacons_not_linked: true
  mac_advanced_searches_no_criteria: true
  mac_advanced_searches_invalid_criteria: true
  mac_applications_no_scope: true
  mac_configuration_profiles_no_scope: true
  mac_devices_duplicate_names: true
  mac_devices_duplicate_serial_numbers: true
  mac_devices_last_check_in: true
  mac_devices_last_inventory: true
  mac_devices_unmanaged: true
  mac_directory_bindings_not_linked: true
  mac_disk_encryptions_not_linked: true
  mac_dock_items_not_linked: true
  mac_extension_attributes_not_linked: true
  mac_extension_attributes_disabled: true
  mac_extension_attributes_linter_warnings: true
  mac_extension_attributes_linter_errors: true
  mac_packages_not_linked: true
  mac_patch_policies_no_scope: true
  mac_patch_policies_disabled: true
  mac_policies_no_scope: true
  mac_policies_disabled: true
  mac_policies_no_payload: true
  mac_policies_jamf_remote: true
  mac_policies_last_executed: true
  mac_policies_failed_threshold: true
  mac_printers_not_linked: true
  mac_restricted_software_no_scope: true
  mac_scripts_not_linked: true
  mac_scripts_linter_warnings: true
  mac_scripts_linter_errors: true
  mac_smart_groups_not_linked: true
  mac_smart_groups_no_criteria: true
  mac_static_groups_not_linked: true
  mac_static_groups_empty: true
  mobile_advanced_searches_no_criteria: true
  mobile_advanced_searches_invalid_criteria: true
  mobile_applications_no_scope: true
  mobile_configuration_profiles_no_scope: true
  mobile_devices_last_inventory: true
  mobile_devices_unmanaged: true
  mobile_extension_attributes_not_linked: true
  mobile_smart_groups_not_linked: true
  mobile_smart_groups_no_criteria: true
  mobile_static_groups_not_linked: true
  mobile_static_groups_empty: true
  network_segments_not_linked: true
report_options:
  mac_devices_last_check_in: 15
  mac_devices_last_inventory: 15
  mac_policies_last_executed: 15
  mac_policies_failed_threshold: 15
  mobile_devices_last_inventory: 15
output:
  json: "/path/to/report.json"
  plist: "/path/to/report.plist"
  yaml: "/path/to/report.yaml"
  markdown: "/path/to/report.md"
  html: "/path/to/report.html"
slack:
  enabled: true
  token: xoxb-your-token
  channel: channel_name_or_id
  text: "Custom Slack message supporting Markdown and Emoji."
  attachments:
    - json
    - plist
    - yaml
    - markdown
    - html
