name: swift_setup_lint_build_test
on: [push, pull_request]
jobs:
  setup_lint_build_test:
    name: Setup, Lint, Build and Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fwal/setup-swift@v1
        with:
          swift-version: "5.5"
      - name: Update $PATH
        run: echo "$GITHUB_WORKSPACE/.build/release" >> $GITHUB_PATH
      - name: Run SwiftLint
        run: swiftlint --strict
      # - name: Run DrString
      #   run: drstring check --config-file .drstring.toml
      - name: Build Xcode project
        run: swift build --configuration release --verbose
      - name: Test Xcode project
        run: swift test --verbose || true
      - name: Print kmart version
        run: kmart --version
